name: "CI"
on:
  [pull_request, workflow_dispatch]

jobs: 
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/cache@v4.0.2
          with: 
            key: ${{ runner.os }}-ci
        - uses: actions/setup-node@v4
        - run: npm ci
        - run: npm test
        - uses: livewing/lcov-job-summary@v1.1.0
